name: Docker Build and Update Release

on:
  release:
    types:
      - published

jobs:
  build-and-update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build-Push Docker image
        id: docker_build_push
        run: |
          TAG_NAME=tomatopunk/clickhouse-benchmark:${{ github.ref_name }}
          docker build --platform linux/amd64 -t $TAG_NAME -f build/Dockerfile .
          docker push $TAG_NAME
          echo "::set-output name=image_name::$TAG_NAME"

      - name: Update release description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releaseName = context.payload.release.name;
            const releaseDescription = context.payload.release.body;
            const imageName = '${{ steps.docker_build_push.outputs.image_name }}';
            const newDescription = `${releaseDescription}\n\nDocker image:${imageName}`;
            const octokit = require('@octokit/rest')();
            octokit.authenticate({
              type: 'token',
              token: process.env.GITHUB_TOKEN
            });
            octokit.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: newDescription
            });
