name: Docker Build and Update Release

on:
  release:
    types:
      - published

jobs:
  build-and-update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          IMAGE_NAME=tomatopunk/clickhouse-benchmark:${{ github.ref }}
          docker build --platform linux/amd64 -t $IMAGE_NAME -f build/Dockerfile .
          echo "::set-output name=image_name::$IMAGE_NAME"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME=${{ needs.build.outputs.image_name }}
          docker push $IMAGE_NAME

      - name: Update release description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releaseName = context.payload.release.name;
            const releaseDescription = context.payload.release.body;
            const newDescription = `${releaseDescription}\n\nDocker image: ${context.payload.repository.owner.login}/${context.payload.repository.name}:${context.payload.release.tag_name}`;
            const octokit = require('@octokit/rest')();
            octokit.authenticate({
              type: 'token',
              token: process.env.GITHUB_TOKEN
            });
            octokit.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: newDescription
            });
